name: "Build the project"

on:
    push:
        branches:
            - build
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            - name: Build the project
              run: npm run build



